apiVersion: apps/v1
kind: Deployment
metadata:
  name: entry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entry
  template:
    metadata:
      labels:
        app: entry
    spec:
      containers:
      - name: entry-container
        image: localhost:5000/count_entry
        ports:
        - containerPort: 8083
        env:
        - name: INSTANCES
          value: "INSTANCE_IP:8083" # INSTANCE_IP should be replace with result from command `kubectl get service/instance -o jsonpath='{.spec.clusterIP}'`
        - name: HOST
          value: ""
        - name: PORT
          value: "8083"

---
apiVersion: v1
kind: Service
metadata:
  name: entry-v2
spec:
  type: NodePort
  selector:
    app: entry
  ports:
  - name: entry
    protocol: TCP
    port: 8083
    targetPort: 8083
    nodePort: 30003