version: '3'
services:
    entry:
        build:
            context: .
            dockerfile: Dockerfile.entry
        environment:
            - HOST=
            - PORT=8083
            - INSTANCES=count_instance_1:8083,count_instance_2:8083,count_instance_3:8083
        ports:
            - 127.0.0.1:8083:8083
        networks:
            - request-count-compose
    instance:
        build:
            context: .
            dockerfile: Dockerfile.instance
        depends_on:
            - entry
        environment:
            - HOST=
            - PORT=8083
        networks:
            - request-count-compose
        deploy:
            mode: replicated
            replicas: 3
            endpoint_mode: vip # dnsrr # NOTE: my docker-compose version is not high enough

networks:
  request-count-compose:
    external: false 