version: '3'
services:
    entry:
        build:
            context: .
            dockerfile: Dockerfile.entry
        environment:
            - HOST=
            - PORT=8083
            - INSTANCES=request-count_instance_1:8083,request-count_instance_2:8083
# TODO: approach INSTANCES in a more scalable way
        ports:
            - 127.0.0.1:8083:8083
        networks:
            - request-count
    instance:
        build:
            context: .
            dockerfile: Dockerfile.instance
        depends_on:
            - entry
        environment:
            - HOST=
            - PORT=8083
            - RECV_HOST=
            - RECV_PORT=8183
            - SEND_HOST=request-count_instance_1
            - SEND_PORT=8183
        networks:
            - request-count
        deploy:
            mode: replicated
            replicas: 3
            endpoint_mode: vip # dnsrr # NOTE: my docker-compose version is not high enough

networks:
  request-count:
    external: true 