apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameInstance }}
  labels:
    {{- toYaml .Values.labelsInstance | nindent 4 }}
spec:
  type: {{ .Values.serviceInstance.type }}
  selector:
    {{- toYaml .Values.selectorLabelsInstance | nindent 4 }}
  ports:
  - name: {{ .Values.fullnameInstance }}
    protocol: {{ .Values.serviceInstance.protocol }}
    port: {{ .Values.serviceInstance.port }}
  clusterIP: {{ .Values.instanceClusterIP }}
