apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameEntry }}
  labels:
    {{- toYaml .Values.labelsEntry | nindent 4 }}
spec:
  type: {{ .Values.serviceEntry.type }}
  selector:
    {{- toYaml .Values.selectorLabelsEntry | nindent 4 }}
  ports:
  - name: {{ .Values.fullnameEntry }}
    protocol: {{ .Values.serviceEntry.protocol }}
    port: {{ .Values.serviceEntry.port }}
    targetPort: {{ .Values.serviceEntry.targetPort }}
    nodePort: {{ .Values.serviceEntry.nodePort }}
